// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace mymdbwebapp.EfCoreModels
{
    public partial class AliasType
    {
        public AliasType()
        {
            TitleAliasesTypes = new HashSet<TitleAliasesType>();
        }

        public int TypeId { get; set; }
        public string TypeName { get; set; }

        public virtual ICollection<TitleAliasesType> TitleAliasesTypes { get; set; }
    }
}