// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace mymdbwebapp.EfCoreModels
{
    public partial class NameBasic
    {
        public NameBasic()
        {
            NamesKnownForTitles = new HashSet<NamesKnownForTitle>();
            NamesProfessions = new HashSet<NamesProfession>();
            TitlePrincipals = new HashSet<TitlePrincipal>();
            TitlesDirectors = new HashSet<TitlesDirector>();
            TitlesWriters = new HashSet<TitlesWriter>();
        }

        public string Nconst { get; set; }
        public string PrimaryName { get; set; }
        public int? BirthYear { get; set; }
        public int? DeathYear { get; set; }

        public virtual ICollection<NamesKnownForTitle> NamesKnownForTitles { get; set; }
        public virtual ICollection<NamesProfession> NamesProfessions { get; set; }
        public virtual ICollection<TitlePrincipal> TitlePrincipals { get; set; }
        public virtual ICollection<TitlesDirector> TitlesDirectors { get; set; }
        public virtual ICollection<TitlesWriter> TitlesWriters { get; set; }
    }
}