// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace mymdbwebapp.EfCoreModels
{
    public partial class NamesProfession
    {
        public string Nconst { get; set; }
        public string Profession { get; set; }

        public virtual NameBasic NconstNavigation { get; set; }
    }
}