// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace mymdbwebapp.EfCoreModels
{
    public partial class TitlesWriter
    {
        public string Tconst { get; set; }
        public string WriterNconst { get; set; }

        public virtual TitleBasic TconstNavigation { get; set; }
        public virtual NameBasic WriterNconstNavigation { get; set; }
    }
}