// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace mymdbwebapp.EfCoreModels
{
    public partial class TitleType
    {
        public TitleType()
        {
            TitleBasics = new HashSet<TitleBasic>();
        }

        public int TypeId { get; set; }
        public string TypeName { get; set; }

        public virtual ICollection<TitleBasic> TitleBasics { get; set; }
    }
}