// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace mymdbwebapp.EfCoreModels
{
    public partial class TitleBasic
    {
        public TitleBasic()
        {
            NamesKnownForTitles = new HashSet<NamesKnownForTitle>();
            TitleAliases = new HashSet<TitleAlias>();
            TitlePrincipals = new HashSet<TitlePrincipal>();
            TitlesDirectors = new HashSet<TitlesDirector>();
            TitlesGenres = new HashSet<TitlesGenre>();
            TitlesWriters = new HashSet<TitlesWriter>();
        }

        public string Tconst { get; set; }
        public int? TitleType { get; set; }
        public string PrimaryTitle { get; set; }
        public string OriginalTitle { get; set; }
        public bool IsAdult { get; set; }
        public int? StartYear { get; set; }
        public int? EndYear { get; set; }
        public int? Runtime { get; set; }

        public virtual TitleType TitleTypeNavigation { get; set; }
        public virtual ICollection<NamesKnownForTitle> NamesKnownForTitles { get; set; }
        public virtual ICollection<TitleAlias> TitleAliases { get; set; }
        public virtual ICollection<TitlePrincipal> TitlePrincipals { get; set; }
        public virtual ICollection<TitlesDirector> TitlesDirectors { get; set; }
        public virtual ICollection<TitlesGenre> TitlesGenres { get; set; }
        public virtual ICollection<TitlesWriter> TitlesWriters { get; set; }
    }
}