// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace mymdbwebapp.EfCoreModels
{
    public partial class TitlePrincipal
    {
        public TitlePrincipal()
        {
            PrincipalsCharacters = new HashSet<PrincipalsCharacter>();
        }

        public int PrincipalId { get; set; }
        public string Tconst { get; set; }
        public string Nconst { get; set; }
        public string Category { get; set; }
        public string Job { get; set; }

        public virtual NameBasic NconstNavigation { get; set; }
        public virtual TitleBasic TconstNavigation { get; set; }
        public virtual ICollection<PrincipalsCharacter> PrincipalsCharacters { get; set; }
    }
}